config/routes.rb
Rails.application.routes.draw do
  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:owner_id, :target, :word_class, :target_sample_0, :target_sample_1, :target_sample_2, :native, :native_sample_0, :native_sample_1, :native_sample_2, :created, :learn_state, :next_schedule, :last_schedule, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Words</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.number_field :owner_id, id: :word_owner_id %>
  </div>

  <div class="field">
    <%= form.label :target %>
    <%= form.text_field :target, id: :word_target %>
  </div>

  <div class="field">
    <%= form.label :word_class %>
    <%= form.text_field :word_class, id: :word_word_class %>
  </div>

  <div class="field">
    <%= form.label :target_sample_0 %>
    <%= form.text_area :target_sample_0, id: :word_target_sample_0 %>
  </div>

  <div class="field">
    <%= form.label :target_sample_1 %>
    <%= form.text_area :target_sample_1, id: :word_target_sample_1 %>
  </div>

  <div class="field">
    <%= form.label :target_sample_2 %>
    <%= form.text_area :target_sample_2, id: :word_target_sample_2 %>
  </div>

  <div class="field">
    <%= form.label :native %>
    <%= form.text_field :native, id: :word_native %>
  </div>

  <div class="field">
    <%= form.label :native_sample_0 %>
    <%= form.text_area :native_sample_0, id: :word_native_sample_0 %>
  </div>

  <div class="field">
    <%= form.label :native_sample_1 %>
    <%= form.text_area :native_sample_1, id: :word_native_sample_1 %>
  </div>

  <div class="field">
    <%= form.label :native_sample_2 %>
    <%= form.text_area :native_sample_2, id: :word_native_sample_2 %>
  </div>

  <div class="field">
    <%= form.label :created %>
    <%= form.date_select :created, id: :word_created %>
  </div>

  <div class="field">
    <%= form.label :learn_state %>
    <%= form.number_field :learn_state, id: :word_learn_state %>
  </div>

  <div class="field">
    <%= form.label :next_schedule %>
    <%= form.date_select :next_schedule, id: :word_next_schedule %>
  </div>

  <div class="field">
    <%= form.label :last_schedule %>
    <%= form.date_select :last_schedule, id: :word_last_schedule %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :word_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Target</th>
      <th>Word class</th>
      <th>Target sample 0</th>
      <th>Target sample 1</th>
      <th>Target sample 2</th>
      <th>Native</th>
      <th>Native sample 0</th>
      <th>Native sample 1</th>
      <th>Native sample 2</th>
      <th>Created</th>
      <th>Learn state</th>
      <th>Next schedule</th>
      <th>Last schedule</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.owner_id %></td>
        <td><%= word.target %></td>
        <td><%= word.word_class %></td>
        <td><%= word.target_sample_0 %></td>
        <td><%= word.target_sample_1 %></td>
        <td><%= word.target_sample_2 %></td>
        <td><%= word.native %></td>
        <td><%= word.native_sample_0 %></td>
        <td><%= word.native_sample_1 %></td>
        <td><%= word.native_sample_2 %></td>
        <td><%= word.created %></td>
        <td><%= word.learn_state %></td>
        <td><%= word.next_schedule %></td>
        <td><%= word.last_schedule %></td>
        <td><%= word.image %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @word.owner_id %>
</p>

<p>
  <strong>Target:</strong>
  <%= @word.target %>
</p>

<p>
  <strong>Word class:</strong>
  <%= @word.word_class %>
</p>

<p>
  <strong>Target sample 0:</strong>
  <%= @word.target_sample_0 %>
</p>

<p>
  <strong>Target sample 1:</strong>
  <%= @word.target_sample_1 %>
</p>

<p>
  <strong>Target sample 2:</strong>
  <%= @word.target_sample_2 %>
</p>

<p>
  <strong>Native:</strong>
  <%= @word.native %>
</p>

<p>
  <strong>Native sample 0:</strong>
  <%= @word.native_sample_0 %>
</p>

<p>
  <strong>Native sample 1:</strong>
  <%= @word.native_sample_1 %>
</p>

<p>
  <strong>Native sample 2:</strong>
  <%= @word.native_sample_2 %>
</p>

<p>
  <strong>Created:</strong>
  <%= @word.created %>
</p>

<p>
  <strong>Learn state:</strong>
  <%= @word.learn_state %>
</p>

<p>
  <strong>Next schedule:</strong>
  <%= @word.next_schedule %>
</p>

<p>
  <strong>Last schedule:</strong>
  <%= @word.last_schedule %>
</p>

<p>
  <strong>Image:</strong>
  <%= @word.image %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>